### ISSUE TITLE
Broken adapter headers 

### ISSUE THREAD

**Issue by Phoscur** [Breeze/breeze.js#65]
I'm still using a modified version of the mongodb dataservice to be able to include it via RequireJS:
```
bower_components/breezejs/adapters/breeze.dataService.mongo.js:4 Uncaught ReferenceError: breeze is not defined
```
Please use coherent fileheaders (main breezejs file has a good one) or at least change line 4 to
```
if (window.breeze) {
```

**Comment by wardbell** [comment]
Good point. I believe I have fixed it in a consistent manner across all breeze adapters and breeze.labs.

You should see this in the next release (projected to be v.1.5.3). Commit c1832a2

**Comment by Phoscur** [comment]
Did this somehow miss the release? I am on 1.5.3 now and it's still the same..

**Comment by wardbell** [comment]
It was fixed. Click on the commit SHA link in my previous comment to see what I mean.

Did you update your bower package? I suspect you're referring to the **deprecated** package (breeze.js.bower) where it is NOT changed.

You should reference the **active** bower package, [***bower-breeze-client***](https://github.com/Breeze/bower-breeze-client).

**Comment by Phoscur** [comment]
Issue is not solved, now it fails line 11.
```Uncaught ReferenceError: breeze is not defined breeze.dataService.mongo.js:11```

**Comment by wardbell** [comment]
Well THAT is embarrassing. The changes are in the source repo (breeze.js) but had not been copied to the bower repo (bower-breeze-client). Apparently these changes were made AFTER v.1.5.3 was released and therefore were not incorporated in the bower-breeze-client package (nor in the npm breeze-client package).

It's coming back to me now. I discussed it internally and the feeling was that these were not sufficiently critical changes to revisit the v.1.5.3 release package. They are slated now for 1.5.4

I just copied them over now to the bower-breeze-client repo but that doesn't help you immediately I don't think. Nor am I willing to issue a special release for this purpose; I'm afraid the demand is just not high enough for us to make an emergency patch release. You will have to endure until 1.5.4.

Sorry for your pains.

**Comment by wardbell** [comment]
I will re-open this issue until it is actually released.

**Comment by Phoscur** [comment]
No worries, I'm staying with my workaround for now until 1.5.4, then we can close this and I can clean it out. Do you want me to test the bower-breeze-client files manually before?

**Comment by wardbell** [comment]
Please do.That would be GREAT.

**Comment by Phoscur** [comment]
New MongoDataService works, no more reference errors (copied it over my workaround). It's still not strict mode compliant though :P

**Comment by wardbell** [comment]
In what respect? We deliberately exclude "use strict" in the preamble function and include it in the body fn.

Ask me why we did this and I can't recall. Perhaps confusion about globals (access ok, assignment is an error).

Do you think it matters?

**Comment by Phoscur** [comment]
It doesn't really matter now as it works, but I would always favor usage of the strict mode, it avoids some common javascript pitfalls, and we wouldn't have had this issue in the first place.

**Comment by Phoscur** [comment]
Landed. Thank you!

**Comment by wardbell** [comment]
Released in v.1.5.4
